Traceback (most recent call last):
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from cycler import cycler
cycler = cycler(color=['#486afb', '#db48d2', '#ff3b90', '#ff6d4d', '#ffa600'])
plt.rc('axes', prop_cycle=cycler)

tvals = np.linspace(0, 3)
l = 3 # lambda parameter

for a in range(1, 6):
    T = gamma(a=a, scale=1/l)
    plt.plot(tvals, T.pdf(tvals), label=rf'$T_{a}$')
plt.xlabel('$t$')
plt.ylabel('probability density')
plt.legend()
plt.tight_layout()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[10], line 9[0m
[1;32m      6[0m l [38;5;241m=[39m [38;5;241m3[39m [38;5;66;03m# lambda parameter[39;00m
[1;32m      8[0m [38;5;28;01mfor[39;00m a [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m1[39m, [38;5;241m6[39m):
[0;32m----> 9[0m     T [38;5;241m=[39m [43mgamma[49m(a[38;5;241m=[39ma, scale[38;5;241m=[39m[38;5;241m1[39m[38;5;241m/[39ml)
[1;32m     10[0m     plt[38;5;241m.[39mplot(tvals, T[38;5;241m.[39mpdf(tvals), label[38;5;241m=[39m[38;5;124mrf[39m[38;5;124m'[39m[38;5;124m$T_[39m[38;5;132;01m{[39;00ma[38;5;132;01m}[39;00m[38;5;124m$[39m[38;5;124m'[39m)
[1;32m     11[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124m$t$[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'gamma' is not defined

