Traceback (most recent call last):
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/johnmyers/opt/anaconda3/envs/python-2023-08-v2/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
params = [ (10, 10), (2, 2) ]
xvals = np.linspace(0.1, 0.9, 9)
probs_list = []

fig, axes = plt.subplots(1, 2, sharey=True)

for i in range(2):
    a = params[i][0]
    b = params[i][1]
    X = beta(a, b)
    
    probs = np.array([X.pdf(x) for x in xvals])
    probs = probs / np.sum(probs)
    probs_list.append(probs)

    expected_val = 0
    for k in range(len(xvals)):
        expected_val += xvals[k] * probs[k]
    
    _, stems, _ = axes[i].stem(xvals, probs, basefmt=' ', markerfmt=' ')
    plt.setp(stems, 'linewidth', 10)
    axes[i].set_ylim(ymin=0)
    axes[i].set_xticks(xvals)
    axes[i].axvline(x=expected_val, color='red', linestyle='--')
    axes[i].set_ylabel('probability')


axes[0].set_xlabel(r'$x$')
axes[1].set_xlabel(r'$x$')
fig.set_size_inches(8, 3)
plt.tight_layout()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 10[0m
[1;32m      8[0m a [38;5;241m=[39m params[i][[38;5;241m0[39m]
[1;32m      9[0m b [38;5;241m=[39m params[i][[38;5;241m1[39m]
[0;32m---> 10[0m X [38;5;241m=[39m [43mbeta[49m(a, b)
[1;32m     12[0m probs [38;5;241m=[39m np[38;5;241m.[39marray([X[38;5;241m.[39mpdf(x) [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m xvals])
[1;32m     13[0m probs [38;5;241m=[39m probs [38;5;241m/[39m np[38;5;241m.[39msum(probs)

[0;31mNameError[0m: name 'beta' is not defined

